services:
  # Nginx Web Server
  nginx:
    image: nginx:stable-alpine
    container_name: mousesql_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PHP Service
  php:
    build:
      context: ./php # Build the image from the Dockerfile in the 'php' directory
    container_name: mousesql_php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: mousesql_postgres
    restart: unless-stopped
    shm_size: 8gb
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PSW}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgres/data:ro

volumes:
  db_data: # This named volume persists database data